
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


PAGE_SIZE = 7

cloudinary.cloud_name=dx4i4a03w
cloudinary.api_key=182786111431744
cloudinary.api_secret=XZdGAV7Kc6Fgu8AKSn-5X1miR1U